---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/biomaks/feederBot

steps:
  - name: build
    image: golang
    environment:
      GOOS: linux
      GOARCH: amd64
    commands:
      - go version
      - go build
      - go test ./...

trigger:
  branch:
    - master
  event:
    - push
