[feeds]
    weather = 'https://weather.gc.ca/rss/battleboard/mb9_e.xml'

[databases]
    [databases.local]
        username = 'alerts'
        collection = 'alerts'
        host = 'localhost'
        port = 27017
        databaseName = 'weather'
    [databases.prod]
        username = 'wpg-db'
        collection = 'alerts'
        host = 'cluster0-txu1v.mongodb.net'
        port = 27017
        databaseName = 'weather'
