// Code generated by mockery v1.0.0. DO NOT EDIT.

package services

import mock "github.com/stretchr/testify/mock"

// MockDatabaseInterface is an autogenerated mock type for the DatabaseInterface type
type MockDatabaseInterface struct {
	mock.Mock
}

// Client provides a mock function with given fields:
func (_m *MockDatabaseInterface) Client() ClientInterface {
	ret := _m.Called()

	var r0 ClientInterface
	if rf, ok := ret.Get(0).(func() ClientInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ClientInterface)
		}
	}

	return r0
}

// Collection provides a mock function with given fields: name
func (_m *MockDatabaseInterface) Collection(name string) CollectionInterface {
	ret := _m.Called(name)

	var r0 CollectionInterface
	if rf, ok := ret.Get(0).(func(string) CollectionInterface); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(CollectionInterface)
		}
	}

	return r0
}
